name = "ba-blinky"
target = "thumbv7em-none-eabihf"
board = "nucleo-h743zi2"
chip = "../../chips/stm32h7"
stacksize = 896

[kernel]
name = "ba-blinky"
requires = {flash = 19936, ram = 2032}
features = ["h743"]

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 3328, ram = 2048}
start = true
stacksize = 1536
notifications = ["fault", "timer"]
extern-regions = [ "sram2", "sram3", "sram4" ]

[tasks.jefe.config.allowed-callers]
set_reset_reason = ["sys"]

[tasks.sys]
name = "drv-stm32xx-sys"
features = ["h743"]
priority = 1
max-sizes = {flash = 1792, ram = 1024}
uses = ["rcc", "gpios", "system_flash"]
start = true
task-slots = ["jefe"]

[tasks.user_leds]
name = "drv-user-leds"
features = ["stm32h7"]
priority = 2
max-sizes = {flash = 1408, ram = 1024} 
start = true
task-slots = ["sys"]
notifications = ["timer"]

[tasks.blinky]
name = "task-blinky"
priority = 3
max-sizes = {flash = 1024, ram = 1024}
start = true
task-slots = ["user_leds"]
notifications = ["timer"]

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true
